//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAnt1.Ant1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public long ClientsID { get; set; }
        public int Sum { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Order Order { get; set; }
    }
}
